### PR TITLE
Kazuya Pyra/Mythra and Sephiroth

### PR DESCRIPTION
**Pull request by ZekePolarisBSH**
fixes https://github.com/Gioman101/FlipperAmiibo/issues/42

### CODE REVIEW

**Comment by ZekePolarisBSH** [comment]
Hopefully I did it correctly.

**Comment by crc8109** [comment]
I don't manage the repo or anything, just know how to use GH.

Looks fine enough! Just wait for any feedback from the repo owners on what else they need before merging.

Bonus points: if you wanna see something cool, write "fixes __insert_issue_number__"; when this gets merged, the issue you opened will be auto-closed! E.g. "fixes #42 "

Hope it helps! And congrats on learning how to create a PR!

**Comment by ZekePolarisBSH** [comment]
Thanks on the congrats, this is still confusing for me but in time I will get used to it.

**Comment by crc8109** [comment]
> Thanks on the congrats, this is still confusing for me but in time I will get used to it.

No worries! Git was made back in the day when ppl would contribute code via USB sticks! So the concepts of remote/upstream or push/pull made more sense/had more context. But these days, it can feel a bit arbitrary.

For now, you learned:

* you create a fork and work of your own version of the code
* when you want to contribute cool stuff back to the source, you create a PR on your own fork, and set it to merge into the target branch  (i.e. main/master or Gioman's repo)
* how to close an issue by ref in a PR (e.g. "fixes....)
* how to do all this on Github's GUI/site

If you feel like you're nebulous on some of these steps, best way to get over the confusion is to just practice it until it's not foreign anymore. 

Specifically, try creating another fork of Gioman's (with a diff name than your other fork). Then change ANYTHING on the new fork (create a dummy file, delete a dummy file, etc).

Now you have Fork 2 that's diff from Fork 1, so you can create a PR among your own branches! This is almost the same thing as when you create a PR on someone else's repo. 

Go back to your repo. Create a PR. Merge Fork2 into Fork1. Then see how the changes in Fork2 were brought over to Fork1. Keep iterating this process until you understand it enough.

Now idea how much exposure you're looking to get with GH/tech. But if you want to see how to do this via a CLI/a great visual aid of what's going on with git, this is the best [tool](https://learngitbranching.js.org/) I can recommend. It does require you know how to use a Terminal, so again, it's dependent on your own exposure and interest. But jic!

**Comment by ZekePolarisBSH** [comment]
I do love using git use it all the time on KALI, long story I rather not get into it because it involves shutting down, what is a safe word to use for this?..... A bad guy type that everyone does not like. A person that targets children?

**Pull request merged**
