### PR TITLE
Add Big_Man, Frye, Shiver, Callie(Alterna), Marie(Alterna), Marina(Side Order), Pearl(Side Order)

### PR DESCRIPTION
**Pull request by professorsugoi**
should all be unlocked. just drag n drop like the rest o7

bin-to-ntag converter used: https://github.com/0xz00n/FlipMiibo
password converter used: https://github.com/turbospok/Flipper-NTAG215-password-converter

### CODE REVIEW

**Comment by jonovate** [comment]
@professorsugoi 
Thanks.

Frye works
The other two fail to register as not Amiibo. I'll keep trying.

**Comment by professorsugoi** [comment]
@jonovate 
> Frye works The other two fail to register as not Amiibo.

hmm, weird that one works but not the others. i’ll look into it more later and replace the files with new ones. in the meantime, happy thanksgiving! :)

**Comment by jonovate** [comment]
> @professorsugoi Thanks.
> 
> Frye works The other two fail to register as not Amiibo. I'll keep trying.

Ok got them registered finally. False alarm.

**Comment by jonovate** [comment]
> @jonovate
> 
> > Frye works The other two fail to register as not Amiibo.
> 
> hmm, weird that one works but not the others. i’ll look into it more later and replace the files with new ones. in the meantime, happy thanksgiving! :)

I got it to work in the end. They are finicky at registration but after 3 times it worked.

**Comment by professorsugoi** [comment]
updated with the Alterna and Side Order amiibo

**Comment by jonovate** [comment]
@professorsugoi Can you bring this branch back? Trying to get the side order/alterna's that were never merged into main.

**Pull request closed without merging**
